"""Authenticated downloads for files generated by the agent."""

from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse

from app.auth import verify_token_dep
from app.config import DATASHEETS_DIR, DOCUMENTS_DIR
from app.security.files import is_within_dir, safe_filename


router = APIRouter(tags=["downloads"])


_MEDIA_TYPES = {
    ".pdf": "application/pdf",
    ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
}


def _download_from(base: Path, filename: str) -> FileResponse:
    clean = safe_filename(filename)
    if clean != filename:
        raise HTTPException(status_code=400, detail="Nombre de archivo inválido")

    target = base / clean
    if not is_within_dir(target, base) or not target.exists() or not target.is_file():
        raise HTTPException(status_code=404, detail="Archivo no encontrado")

    return FileResponse(
        target,
        media_type=_MEDIA_TYPES.get(target.suffix.lower(), "application/octet-stream"),
        filename=target.name,
    )


@router.get("/documents/{filename}")
def download_document(filename: str, _user: str = Depends(verify_token_dep)):
    return _download_from(DOCUMENTS_DIR, filename)


@router.get("/datasheets/{filename}")
def download_datasheet(filename: str, _user: str = Depends(verify_token_dep)):
    return _download_from(DATASHEETS_DIR, filename)
